#! /bin/bash
mkdir data
mkdir models
cd data
mkdir pretrained_model
mkdir VOCdevkit2007
cd VOCdevkit2007
mkdir VOC2007
cd VOC2007
mkdir Annotations
mkdir ImageSets
mkdir JPEGImages
cd ImageSets
mkdir Main
cd ../../../..
cd models
mkdir vgg16
cd vgg16
mkdir pascal_voc
